// Database semplificato di province italiane (esempio ridotto)
export const italianProvinces = [
  { code: 'AG', name: 'Agrigento', region: 'Sicilia' },
  { code: 'AL', name: 'Alessandria', region: 'Piemonte' },
  { code: 'AN', name: 'Ancona', region: 'Marche' },
  { code: 'AO', name: 'Aosta', region: 'Valle d\'Aosta' },
  { code: 'AR', name: 'Arezzo', region: 'Toscana' },
  { code: 'AP', name: 'Ascoli Piceno', region: 'Marche' },
  { code: 'AT', name: 'Asti', region: 'Piemonte' },
  { code: 'AV', name: 'Avellino', region: 'Campania' },
  { code: 'BA', name: 'Bari', region: 'Puglia' },
  { code: 'BT', name: 'Barletta-Andria-Trani', region: 'Puglia' },
  { code: 'BL', name: 'Belluno', region: 'Veneto' },
  { code: 'BN', name: 'Benevento', region: 'Campania' },
  { code: 'BG', name: 'Bergamo', region: 'Lombardia' },
  { code: 'BI', name: 'Biella', region: 'Piemonte' },
  { code: 'BO', name: 'Bologna', region: 'Emilia-Romagna' },
  { code: 'BZ', name: 'Bolzano', region: 'Trentino-Alto Adige' },
  { code: 'BS', name: 'Brescia', region: 'Lombardia' },
  { code: 'BR', name: 'Brindisi', region: 'Puglia' },
  { code: 'CA', name: 'Cagliari', region: 'Sardegna' },
  { code: 'CL', name: 'Caltanissetta', region: 'Sicilia' },
  { code: 'CB', name: 'Campobasso', region: 'Molise' },
  { code: 'CE', name: 'Caserta', region: 'Campania' },
  { code: 'CT', name: 'Catania', region: 'Sicilia' },
  { code: 'CZ', name: 'Catanzaro', region: 'Calabria' },
  { code: 'CH', name: 'Chieti', region: 'Abruzzo' },
  { code: 'CO', name: 'Como', region: 'Lombardia' },
  { code: 'CS', name: 'Cosenza', region: 'Calabria' },
  { code: 'CR', name: 'Cremona', region: 'Lombardia' },
  { code: 'KR', name: 'Crotone', region: 'Calabria' },
  { code: 'CN', name: 'Cuneo', region: 'Piemonte' },
  { code: 'EN', name: 'Enna', region: 'Sicilia' },
  { code: 'FM', name: 'Fermo', region: 'Marche' },
  { code: 'FE', name: 'Ferrara', region: 'Emilia-Romagna' },
  { code: 'FI', name: 'Firenze', region: 'Toscana' },
  { code: 'FG', name: 'Foggia', region: 'Puglia' },
  { code: 'FC', name: 'Forlì-Cesena', region: 'Emilia-Romagna' },
  { code: 'FR', name: 'Frosinone', region: 'Lazio' },
  { code: 'GE', name: 'Genova', region: 'Liguria' },
  { code: 'GO', name: 'Gorizia', region: 'Friuli-Venezia Giulia' },
  { code: 'GR', name: 'Grosseto', region: 'Toscana' },
  { code: 'IM', name: 'Imperia', region: 'Liguria' },
  { code: 'IS', name: 'Isernia', region: 'Molise' },
  { code: 'SP', name: 'La Spezia', region: 'Liguria' },
  { code: 'AQ', name: 'L\'Aquila', region: 'Abruzzo' },
  { code: 'LT', name: 'Latina', region: 'Lazio' },
  { code: 'LE', name: 'Lecce', region: 'Puglia' },
  { code: 'LC', name: 'Lecco', region: 'Lombardia' },
  { code: 'LI', name: 'Livorno', region: 'Toscana' },
  { code: 'LO', name: 'Lodi', region: 'Lombardia' },
  { code: 'LU', name: 'Lucca', region: 'Toscana' },
  { code: 'MC', name: 'Macerata', region: 'Marche' },
  { code: 'MN', name: 'Mantova', region: 'Lombardia' },
  { code: 'MS', name: 'Massa-Carrara', region: 'Toscana' },
  { code: 'MT', name: 'Matera', region: 'Basilicata' },
  { code: 'ME', name: 'Messina', region: 'Sicilia' },
  { code: 'MI', name: 'Milano', region: 'Lombardia' },
  { code: 'MO', name: 'Modena', region: 'Emilia-Romagna' },
  { code: 'MB', name: 'Monza e Brianza', region: 'Lombardia' },
  { code: 'NA', name: 'Napoli', region: 'Campania' },
  { code: 'NO', name: 'Novara', region: 'Piemonte' },
  { code: 'NU', name: 'Nuoro', region: 'Sardegna' },
  { code: 'OR', name: 'Oristano', region: 'Sardegna' },
  { code: 'PD', name: 'Padova', region: 'Veneto' },
  { code: 'PA', name: 'Palermo', region: 'Sicilia' },
  { code: 'PR', name: 'Parma', region: 'Emilia-Romagna' },
  { code: 'PV', name: 'Pavia', region: 'Lombardia' },
  { code: 'PG', name: 'Perugia', region: 'Umbria' },
  { code: 'PU', name: 'Pesaro e Urbino', region: 'Marche' },
  { code: 'PE', name: 'Pescara', region: 'Abruzzo' },
  { code: 'PC', name: 'Piacenza', region: 'Emilia-Romagna' },
  { code: 'PI', name: 'Pisa', region: 'Toscana' },
  { code: 'PT', name: 'Pistoia', region: 'Toscana' },
  { code: 'PN', name: 'Pordenone', region: 'Friuli-Venezia Giulia' },
  { code: 'PZ', name: 'Potenza', region: 'Basilicata' },
  { code: 'PO', name: 'Prato', region: 'Toscana' },
  { code: 'RG', name: 'Ragusa', region: 'Sicilia' },
  { code: 'RA', name: 'Ravenna', region: 'Emilia-Romagna' },
  { code: 'RC', name: 'Reggio Calabria', region: 'Calabria' },
  { code: 'RE', name: 'Reggio Emilia', region: 'Emilia-Romagna' },
  { code: 'RI', name: 'Rieti', region: 'Lazio' },
  { code: 'RN', name: 'Rimini', region: 'Emilia-Romagna' },
  { code: 'RM', name: 'Roma', region: 'Lazio' },
  { code: 'RO', name: 'Rovigo', region: 'Veneto' },
  { code: 'SA', name: 'Salerno', region: 'Campania' },
  { code: 'SS', name: 'Sassari', region: 'Sardegna' },
  { code: 'SV', name: 'Savona', region: 'Liguria' },
  { code: 'SI', name: 'Siena', region: 'Toscana' },
  { code: 'SR', name: 'Siracusa', region: 'Sicilia' },
  { code: 'SO', name: 'Sondrio', region: 'Lombardia' },
  { code: 'SU', name: 'Sud Sardegna', region: 'Sardegna' },
  { code: 'TA', name: 'Taranto', region: 'Puglia' },
  { code: 'TE', name: 'Teramo', region: 'Abruzzo' },
  { code: 'TR', name: 'Terni', region: 'Umbria' },
  { code: 'TO', name: 'Torino', region: 'Piemonte' },
  { code: 'TP', name: 'Trapani', region: 'Sicilia' },
  { code: 'TN', name: 'Trento', region: 'Trentino-Alto Adige' },
  { code: 'TV', name: 'Treviso', region: 'Veneto' },
  { code: 'TS', name: 'Trieste', region: 'Friuli-Venezia Giulia' },
  { code: 'UD', name: 'Udine', region: 'Friuli-Venezia Giulia' },
  { code: 'VA', name: 'Varese', region: 'Lombardia' },
  { code: 'VE', name: 'Venezia', region: 'Veneto' },
  { code: 'VB', name: 'Verbano-Cusio-Ossola', region: 'Piemonte' },
  { code: 'VC', name: 'Vercelli', region: 'Piemonte' },
  { code: 'VR', name: 'Verona', region: 'Veneto' },
  { code: 'VV', name: 'Vibo Valentia', region: 'Calabria' },
  { code: 'VI', name: 'Vicenza', region: 'Veneto' },
  { code: 'VT', name: 'Viterbo', region: 'Lazio' }
];

// Database semplificato delle principali città italiane
export const italianCities: Record<string, string[]> = {
  'AG': ['Agrigento', 'Sciacca', 'Licata', 'Canicattì'],
  'AL': ['Alessandria', 'Casale Monferrato', 'Novi Ligure', 'Tortona'],
  'AN': ['Ancona', 'Senigallia', 'Jesi', 'Fabriano'],
  'AO': ['Aosta', 'Saint-Vincent', 'Courmayeur', 'Châtillon'],
  'AR': ['Arezzo', 'Cortona', 'Sansepolcro', 'Montevarchi'],
  'AP': ['Ascoli Piceno', 'San Benedetto del Tronto', 'Grottammare', 'Folignano'],
  'AT': ['Asti', 'Nizza Monferrato', 'Canelli', 'San Damiano d\'Asti'],
  'AV': ['Avellino', 'Ariano Irpino', 'Montella', 'Solofra'],
  'BA': ['Bari', 'Altamura', 'Monopoli', 'Molfetta'],
  'BT': ['Barletta', 'Andria', 'Trani', 'Bisceglie'],
  'BL': ['Belluno', 'Feltre', 'Cortina d\'Ampezzo', 'Agordo'],
  'BN': ['Benevento', 'Montesarchio', 'Sant\'Agata de\' Goti', 'Telese Terme'],
  'BG': ['Bergamo', 'Treviglio', 'Seriate', 'Dalmine'],
  'BI': ['Biella', 'Cossato', 'Trivero', 'Vigliano Biellese'],
  'BO': ['Bologna', 'Imola', 'Casalecchio di Reno', 'San Lazzaro di Savena'],
  'BZ': ['Bolzano', 'Merano', 'Bressanone', 'Laives'],
  'BS': ['Brescia', 'Desenzano del Garda', 'Montichiari', 'Lumezzane'],
  'BR': ['Brindisi', 'Fasano', 'Ostuni', 'Francavilla Fontana'],
  'CA': ['Cagliari', 'Quartu Sant\'Elena', 'Selargius', 'Monserrato'],
  'CL': ['Caltanissetta', 'Gela', 'Niscemi', 'San Cataldo'],
  'CB': ['Campobasso', 'Termoli', 'Bojano', 'Larino'],
  'CE': ['Caserta', 'Aversa', 'Marcianise', 'Santa Maria Capua Vetere'],
  'CT': ['Catania', 'Acireale', 'Misterbianco', 'Paternò'],
  'CZ': ['Catanzaro', 'Lamezia Terme', 'Soverato', 'Sellia Marina'],
  'CH': ['Chieti', 'Vasto', 'Lanciano', 'Francavilla al Mare'],
  'CO': ['Como', 'Cantù', 'Mariano Comense', 'Erba'],
  'CS': ['Cosenza', 'Rende', 'Corigliano-Rossano', 'Paola'],
  'CR': ['Cremona', 'Crema', 'Casalmaggiore', 'Soresina'],
  'KR': ['Crotone', 'Isola di Capo Rizzuto', 'Cirò Marina', 'Cutro'],
  'CN': ['Cuneo', 'Alba', 'Bra', 'Mondovì'],
  'EN': ['Enna', 'Nicosia', 'Piazza Armerina', 'Leonforte'],
  'FM': ['Fermo', 'Porto Sant\'Elpidio', 'Sant\'Elpidio a Mare', 'Porto San Giorgio'],
  'FE': ['Ferrara', 'Cento', 'Comacchio', 'Argenta'],
  'FI': ['Firenze', 'Scandicci', 'Sesto Fiorentino', 'Empoli'],
  'FG': ['Foggia', 'Cerignola', 'Manfredonia', 'San Severo'],
  'FC': ['Forlì', 'Cesena', 'Cesenatico', 'Savignano sul Rubicone'],
  'FR': ['Frosinone', 'Cassino', 'Sora', 'Alatri'],
  'GE': ['Genova', 'Rapallo', 'Chiavari', 'Sestri Levante'],
  'GO': ['Gorizia', 'Monfalcone', 'Ronchi dei Legionari', 'Cormons'],
  'GR': ['Grosseto', 'Follonica', 'Orbetello', 'Castiglione della Pescaia'],
  'IM': ['Imperia', 'Sanremo', 'Ventimiglia', 'Taggia'],
  'IS': ['Isernia', 'Venafro', 'Agnone', 'Sesto Campano'],
  'SP': ['La Spezia', 'Sarzana', 'Lerici', 'Santo Stefano di Magra'],
  'AQ': ['L\'Aquila', 'Avezzano', 'Sulmona', 'Castel di Sangro'],
  'LT': ['Latina', 'Aprilia', 'Terracina', 'Formia'],
  'LE': ['Lecce', 'Nardò', 'Galatina', 'Casarano'],
  'LC': ['Lecco', 'Merate', 'Calolziocorte', 'Casatenovo'],
  'LI': ['Livorno', 'Piombino', 'Cecina', 'Rosignano Marittimo'],
  'LO': ['Lodi', 'Codogno', 'Casalpusterlengo', 'Sant\'Angelo Lodigiano'],
  'LU': ['Lucca', 'Viareggio', 'Capannori', 'Camaiore'],
  'MC': ['Macerata', 'Civitanova Marche', 'Recanati', 'Tolentino'],
  'MN': ['Mantova', 'Castiglione delle Stiviere', 'Suzzara', 'Viadana'],
  'MS': ['Massa', 'Carrara', 'Montignoso', 'Aulla'],
  'MT': ['Matera', 'Policoro', 'Pisticci', 'Bernalda'],
  'ME': ['Messina', 'Barcellona Pozzo di Gotto', 'Milazzo', 'Patti'],
  'MI': ['Milano', 'Sesto San Giovanni', 'Cinisello Balsamo', 'Legnano'],
  'MO': ['Modena', 'Carpi', 'Sassuolo', 'Formigine'],
  'MB': ['Monza', 'Seregno', 'Lissone', 'Desio'],
  'NA': ['Napoli', 'Giugliano in Campania', 'Torre del Greco', 'Pozzuoli'],
  'NO': ['Novara', 'Borgomanero', 'Galliate', 'Trecate'],
  'NU': ['Nuoro', 'Siniscola', 'Macomer', 'Dorgali'],
  'OR': ['Oristano', 'Terralba', 'Cabras', 'Bosa'],
  'PD': ['Padova', 'Albignasego', 'Vigonza', 'Selvazzano Dentro'],
  'PA': ['Palermo', 'Bagheria', 'Carini', 'Monreale'],
  'PR': ['Parma', 'Fidenza', 'Salsomaggiore Terme', 'Collecchio'],
  'PV': ['Pavia', 'Vigevano', 'Voghera', 'Stradella'],
  'PG': ['Perugia', 'Foligno', 'Città di Castello', 'Spoleto'],
  'PU': ['Pesaro', 'Fano', 'Urbino', 'Fossombrone'],
  'PE': ['Pescara', 'Montesilvano', 'Spoltore', 'Città Sant\'Angelo'],
  'PC': ['Piacenza', 'Fiorenzuola d\'Arda', 'Castel San Giovanni', 'Rottofreno'],
  'PI': ['Pisa', 'Pontedera', 'San Giuliano Terme', 'Cascina'],
  'PT': ['Pistoia', 'Montecatini Terme', 'Monsummano Terme', 'Quarrata'],
  'PN': ['Pordenone', 'Sacile', 'Cordenons', 'Azzano Decimo'],
  'PZ': ['Potenza', 'Melfi', 'Lauria', 'Lavello'],
  'PO': ['Prato', 'Montemurlo', 'Carmignano', 'Poggio a Caiano'],
  'RG': ['Ragusa', 'Modica', 'Vittoria', 'Comiso'],
  'RA': ['Ravenna', 'Faenza', 'Lugo', 'Cervia'],
  'RC': ['Reggio Calabria', 'Gioia Tauro', 'Palmi', 'Villa San Giovanni'],
  'RE': ['Reggio Emilia', 'Correggio', 'Scandiano', 'Guastalla'],
  'RI': ['Rieti', 'Fara in Sabina', 'Cittaducale', 'Contigliano'],
  'RN': ['Rimini', 'Riccione', 'Santarcangelo di Romagna', 'Bellaria-Igea Marina'],
  'RM': ['Roma', 'Fiumicino', 'Civitavecchia', 'Guidonia Montecelio'],
  'RO': ['Rovigo', 'Adria', 'Lendinara', 'Porto Viro'],
  'SA': ['Salerno', 'Cava de\' Tirreni', 'Battipaglia', 'Nocera Inferiore'],
  'SS': ['Sassari', 'Alghero', 'Porto Torres', 'Ozieri'],
  'SV': ['Savona', 'Albenga', 'Varazze', 'Cairo Montenotte'],
  'SI': ['Siena', 'Poggibonsi', 'Colle di Val d\'Elsa', 'Montepulciano'],
  'SR': ['Siracusa', 'Augusta', 'Avola', 'Noto'],
  'SO': ['Sondrio', 'Tirano', 'Morbegno', 'Livigno'],
  'SU': ['Carbonia', 'Iglesias', 'Assemini', 'Capoterra'],
  'TA': ['Taranto', 'Martina Franca', 'Massafra', 'Grottaglie'],
  'TE': ['Teramo', 'Giulianova', 'Roseto degli Abruzzi', 'Atri'],
  'TR': ['Terni', 'Orvieto', 'Narni', 'Amelia'],
  'TO': ['Torino', 'Moncalieri', 'Rivoli', 'Collegno'],
  'TP': ['Trapani', 'Marsala', 'Mazara del Vallo', 'Alcamo'],
  'TN': ['Trento', 'Rovereto', 'Pergine Valsugana', 'Arco'],
  'TV': ['Treviso', 'Conegliano', 'Castelfranco Veneto', 'Montebelluna'],
  'TS': ['Trieste', 'Muggia', 'Duino-Aurisina', 'San Dorligo della Valle'],
  'UD': ['Udine', 'Codroipo', 'Cervignano del Friuli', 'Latisana'],
  'VA': ['Varese', 'Busto Arsizio', 'Gallarate', 'Saronno'],
  'VE': ['Venezia', 'Chioggia', 'San Donà di Piave', 'Mira'],
  'VB': ['Verbania', 'Domodossola', 'Gravellona Toce', 'Omegna'],
  'VC': ['Vercelli', 'Borgosesia', 'Santhià', 'Crescentino'],
  'VR': ['Verona', 'Villafranca di Verona', 'San Bonifacio', 'Legnago'],
  'VV': ['Vibo Valentia', 'Tropea', 'Serra San Bruno', 'Nicotera'],
  'VI': ['Vicenza', 'Bassano del Grappa', 'Schio', 'Arzignano'],
  'VT': ['Viterbo', 'Civita Castellana', 'Tarquinia', 'Montefiascone']
};

// Funzioni di utilità

// Ottieni la lista di tutte le province
export const getProvinces = () => {
  return italianProvinces.map(province => ({
    value: province.code,
    label: `${province.name} (${province.code})`,
  }));
};

// Ottieni la lista di città per una provincia
export const getCitiesByProvince = (provinceCode: string) => {
  if (!provinceCode) return [];
  const cities = italianCities[provinceCode] || [];
  return cities.map(city => ({
    value: city,
    label: city,
  }));
};

// Ottieni il codice provincia dal nome
export const getProvinceCodeByName = (provinceName: string) => {
  const province = italianProvinces.find(p => p.name === provinceName);
  return province ? province.code : null;
};

// Ottieni il nome provincia dal codice
export const getProvinceNameByCode = (provinceCode: string) => {
  const province = italianProvinces.find(p => p.code === provinceCode);
  return province ? province.name : null;
};

// Ottieni la regione dal codice provincia
export const getRegionByProvinceCode = (provinceCode: string) => {
  const province = italianProvinces.find(p => p.code === provinceCode);
  return province ? province.region : null;
};

// Controlla se una città esiste in una provincia
export const isCityInProvince = (city: string, provinceCode: string) => {
  if (!provinceCode || !city) return false;
  const cities = italianCities[provinceCode] || [];
  return cities.includes(city);
};